### ISSUE TITLE
map_tutorial.ipynb

### ISSUE THREAD

**Issue by tom-bu** [argoai/av2-api#34]
In your map_tutorial.ipynb, I encountered some issues: 
`from av2.datasets.sensor_dataset.av2_sensor_dataloader import AV2SensorDataLoader`
should be 
`from av2.datasets.sensor.av2_sensor_dataloader import AV2SensorDataLoader`

Each instance of ` ArgoverseStaticMap.from_json()` should be ` ArgoverseStaticMap.from_map_dir()`

And then `args` should be like

`from pathlib import Path`
`args = SimpleNamespace(**{"dataroot": Path(dataroot), "log_id": Path(log_id)})`

**Comment by benjaminrwilson** [comment]
Thanks for pointing this out, @tom-bu. Would you mind checking to see if this PR fixes the issues for you? https://github.com/argoai/av2-api/pull/35

**Comment by tom-bu** [comment]
Yes, I believe it's fixed now.
