### ISSUE TITLE
[Question] Waymo Open Motion Dataset to Argoverse Forecasting Dataset Converter?

### ISSUE THREAD

**Issue by manolotis** [argoai/av2-api#42]
Hi!

I see the [previous version](https://github.com/argoai/argoverse-api) of the argoverse datasets has some interesting open-source converters from other dataset formats (e.g. [Waymo to Argoverse](https://github.com/johnwlambert/waymo_to_argoverse). Are there any plans to release a Waymo Open Motion Dataset to Argoverse Forecasting dataset converter? I would find it really useful.

**Comment by wqi** [comment]
Hi @manolotis , thanks for expressing your interest in AV2!

We agree that the availability of dataset adapters/converters would be of significant benefit to the research community and recognize that adapting methods to run on different data types can be time-consuming. To address these issues, we're actively exploring options to improve interoperability and reduce friction between motion forecasting datasets.

We unfortunately don't have anything ready to announce at this time, but will be sure to announce on our [mailing list](https://www.argoverse.org/) if related tooling is released in the future.
