### ISSUE TITLE
Baseline models

### ISSUE THREAD

**Issue by Cram3r95** [argoai/av2-api#55]
Hi guys,

Do you know if some GNN based baseline methods are going to be implemented in the tutorial? Similar than NN and LSTM for Argoverse 1.0 API, in order to know how to deal with the vectorized map.

**Comment by wqi** [comment]
Hi @Cram3r95, thanks for your interest in the AV2 MF dataset! It is in the cards to update the [WIMP](https://github.com/wqi/WIMP) baseline with a preprocessing script compatible with AV2, but we don't have an ETA quite yet.

We'll be sure to update this issue when the baseline is ready.

**Comment by Cram3r95** [comment]
Hi @wqi, that would be fantastic, since AV2 presents more information in order to leverage the vectorized hdmap, so GNNs could be a good option. Thank you!
