### ISSUE TITLE
Are there some baselines provided for av2?

### ISSUE THREAD

**Issue by ShunliRen** [argoai/av2-api#56]
Are there some baselines provided for av2? for 3d object detection task

**Comment by benjaminrwilson** [comment]
Hi @ShunliRen,

Yes, the 3d object detection baseline can be found here: https://github.com/benjaminrwilson/torchbox3d.

Ben

**Comment by benjaminrwilson** [comment]
Let me know if you have any questions!

**Comment by ShunliRen** [comment]
thanks！
