### ISSUE TITLE
When will the Argoverse 2: 3D Object Detection Competition ends ?

### ISSUE THREAD

**Issue by Icecream-blue-sky** [argoai/av2-api#60]
I would like to confirm if the competition ends on June 13 ？

**Comment by James-Hays** [comment]
Hi,

Yes, all competitions ([Stereo](https://eval.ai/challenge/1704/overview), [Motion Forecasting](https://eval.ai/challenge/1719/overview), [3D Object Detection](https://eval.ai/challenge/1710/overview)) end on 11:59PM EST on June 13th, 2022. The leaderboards will stay online, though.

**Comment by Icecream-blue-sky** [comment]
Two friendly advice: 1、The website(https://cvpr2022.wad.vision/) still shows that the game has not started, which I think will mislead some people. 
![image](https://user-images.githubusercontent.com/26771037/169445273-02ff3043-0fdc-43cc-b22a-afa44705bfa3.png)
2、Why not publish the contest in codalab? I find it difficult to find the entrance to this contest (at least not as easy as codalab), I think that's why this contest has a low number of entries.
