### ISSUE TITLE
'UNKNOWN' is not a valid LaneMarkType in v0.2.0

### ISSUE THREAD

**Issue by godture** [argoai/av2-api#66]
Hi,
I get the following error running code `ArgoverseStaticMap.from_json(static_map_path)` with certain map files:
`ValueError: 'UNKNOWN' is not a valid LaneMarkType`
The version of av2 is 0.2.0.
When I check the LaneMarkType class while running, I notice that it does not have the member "UNKNOWN", which exists in the github code.
Could you please check and fix it in the released version?

**Comment by karthi0804** [comment]
Please let me know if there is a quick fix.

**Comment by wqi** [comment]
Hi folks, we just released AV2 v0.2.1 to PyPI that includes the fix for this issue - please try updating your API package.

If you're still experiencing issues, please feel free to re-open this issue. :-)
