### ISSUE TITLE
About Motion Forecasting Dataset

### ISSUE THREAD

**Issue by Zhikaiiii** [argoai/av2-api#67]
I wonder whether there is roundabout scenario in this Dataset? 
Much thanks to your reply :)

**Comment by wqi** [comment]
Hi @Zhikaiiii, the AV2 motion forecasting dataset covers a wide variety of road features across 6 different US metro areas. This includes more than a few scenarios located at roundabouts, but we don't currently provide any explicit labels for scenarios of this type.

For more information about the geographic distribution of scenarios included with the AV2 MF dataset, please see the figures below:
![miami](https://user-images.githubusercontent.com/6446818/172487889-d15ce172-d953-40e8-a57a-0532289eb8e3.png)
![palo-alto](https://user-images.githubusercontent.com/6446818/172487898-7e220ffa-58c4-4f0f-a477-dac6f7c64fc7.png)
![pittsburgh](https://user-images.githubusercontent.com/6446818/172487907-0f61b5c0-f517-4a4f-9d29-65366f2f0f31.png)
![wdc](https://user-images.githubusercontent.com/6446818/172487917-5e46e2c5-6083-4f4b-a066-a8825fc36e28.png)
![dearborn](https://user-images.githubusercontent.com/6446818/172487933-9f1a1933-19ff-43c9-8a87-a7eabb8cf5e8.png)
![austin](https://user-images.githubusercontent.com/6446818/172487874-f59613ce-aaa9-4fad-a08d-987fe140e5a3.png)
