### ISSUE TITLE
About Motion Forecasting Challenge Submission

### ISSUE THREAD

**Issue by mikezhang95** [argoai/av2-api#68]
Hi! I am about to make a submission to the motion forecasting challenge (https://eval.ai/challenge/1719/my-submissions) but got an error "KeyError(1)" from Stderr File. Is there any way to get a detailed error message?

**Comment by chch9907** [comment]
I also got this issue and I found it was because my predictions did not include all the scenarios in test data, which might result from the data preprocessing.  Actually, scenario id is the key of the dict you submit. Hope it could help you.

**Comment by mikezhang95** [comment]
> I also got this issue and I found it was because my predictions did not include all the scenarios in test data, which might result from the data preprocessing. Actually, scenario id is the key of the dict you submit. Hope it could help you.

Thanks for replying. Your suggestion solves my problem. I can submit now.
