### ISSUE TITLE
Submission Options: "Upload File" Option can not choose .parquet file

### ISSUE THREAD

**Issue by kingwmk** [argoai/av2-api#74]
Hello, I found Submission Options: "Upload File" Option can not choose .parquet file which is needed for leaderboard evaluation.

**Comment by Thomas0Gilles** [comment]
For information if others meet the same problem, I also had it: the website says it expects a json or zip file but you can change the filter to all files in the file explorer and upload the parquet file anyway, despite the page warning it should work.
