### ISSUE TITLE
submission file format

### ISSUE THREAD

**Issue by hendrik-b** [argoai/av2-api#76]
The ChallengeSubmission class of av2 generates parquet files - but eval.ai only accepts json, zip, gz, txt, csv, tsv, ... (via file upload)
What file name is required? Which file name extension?
I tried to zip the submission.parquet file as well as changing the compression in submission_df.to_parquet(submission_file_path, compression='gzip' ) and storing as .gz but neither if those works.

**Comment by wqi** [comment]
Looks like this has been fixed. Using the latest version of EvalAI, I was not able to reproduce this issue with the AV2 challenge. 

If this issue recurs in the future, please feel free to re-open this issue or open a new one! :-)
