### ISSUE TITLE
Fail to submit to the motion forecasting leaderboard

### ISSUE THREAD

**Issue by ZikangZhou** [argoai/av2-api#79]
Hi @wqi,

Is the motion forecasting leaderboard open now? I tried to submit to it, but the status is always "running".

**Comment by wqi** [comment]
Hello @ZikangZhou, thanks for reaching out. We are aware of the issue and working to get things back online.

**Comment by wqi** [comment]
The motion forecasting leaderboard should be back online now! Please feel free to re-open this issue if you're still facing problems. :-)
