### ISSUE TITLE
Will the motion forcasting challenge be updated for multiple classes and multiple agents forcasting?

### ISSUE THREAD

**Issue by ocean1211** [argoai/av2-api#80]
The challenge of av2 is now with the same setup as the challenge of av1, would your team update it for more setups such as the multiple class or multi-agent trajectory prediction in the future? If your team has such a plan, when would it be released?

Thanks a lot for your work and the new dataset!

**Comment by wqi** [comment]
We do have plans to launch the next iteration of the AV2 MF challenge with an evaluation scheme based on multi-class, multi-agent forecasting, but unfortunately don't have a firm date to share yet. 

As always, we appreciate interest from the community regarding the Argoverse challenges and encourage you to subscribe to our [mailing list](https://www.argoverse.org/index.html) for the most up-to-date information on future updates.
