### ISSUE TITLE
What are the unit for the position: (x, y) attributes ?

### ISSUE THREAD

**Issue by sop12** [argoai/av2-api#93]
Thanks very much for making this great data available to researchers.
I'm working with the Motion Forecasting Dataset. I observed that, when it comes to compute ADE or FDE metric, the unit for the position attributes doesn't matter. But I'm actually working in a project where I should compute the RMSE for both position (x,y) and speed (x,y). I must then compare the results to others experiments results, but I can't do that for position attributes, as I don't know what the units for the position attributes are. It's clearly mentioned in paper and also here in GitHub that velocity it's in m/s, but for Position (x,y), I didn't find any clear information about the unit (is it in meter, centimeter, millimeter or something else?). Thanks for assist

**Comment by wqi** [comment]
Hi @sop12, the units for coordinates in the AV2 MF dataset are in meters with respect to a fixed origin in each city.
